# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d42bfc4682fe9c5ab3367a65641565d45ee359fe131f45655cae23def277119998fa4689805b125b7ecf193691fd83b7e54b3849979d842935c6457a34812a

test:
  secret_key_base: fbd77e61318d296c385a29ae803c485172f1cd7698ff3c30a6472838827ae7c1b2bd07ca97cbff0bd34ce0c8527ab0f22d45b4ef1fd95529f7b3e9fb2847649b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
